"""
Django settings for toptool project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from pathlib import Path
from typing import Optional

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME"  # nosec: different in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []

# Auth
LOGIN_URL = "/login/"
LOGOUT_URL = "/logout/"
LOGIN_REDIRECT_URL_FAILURE = "/login/failed"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

USE_KEYCLOAK: Optional[bool] = None

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_compref_keycloak",
    "django_bootstrap5",
    "bootstrap_datepicker_plus",
    "active_link",
    "email_obfuscator",
    "ckeditor",
    "django_user_agents",
    "toptool",
    "meetingtypes",
    "meetings",
    "tops",
    "protokolle",
    "persons",
    "userprofile",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "toptool.middleware.UpcomingMeetingsMiddleware",
]

ROOT_URLCONF = "toptool.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "toptool.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization

LANGUAGE_CODE = "de-de"
LOCALE_NAME = "de"

LOCALE_PATHS = (BASE_DIR / "locale",)

LANGUAGES = (
    ("de", _("Deutsch")),
    ("en", _("Englisch")),
)

TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_L10N = True
USE_TZ = True
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."

# Media files (in this case: Protokolle)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "node_modules",
    BASE_DIR / "staticfiles",
]

# editor for text fields
CKEDITOR_CONFIGS = {
    "default": {
        "width": "auto",
        "toolbar": "Custom",
        "toolbar_Custom": [
            ["Bold", "Italic", "Underline"],
            ["Undo", "Redo"],
            ["NumberedList", "BulletedList", "-", "Outdent", "Indent"],
            ["Link", "Unlink"],
            ["Source"],
        ],
        "entities": False,
        "basicEntities": False,
    },
}

# Bootstrap config
BOOTSTRAP5 = {
    "required_css_class": "required",
}

# allowed file types for attachments
ALLOWED_FILE_TYPES: dict[str, str] = {
    "pdf": "application/pdf",
    "ods": "application/vnd.oasis.opendocument.spreadsheet",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
}

# Etherpad settings
# to disable etherpad integration set ETHERPAD_API_URL = None
ETHERPAD_API_URL = "http://localhost:9001/api"
ETHERPAD_PAD_URL = "http://localhost:9001/p/"
# the API key from APIKEY.txt in the etherpad installation
ETHERPAD_APIKEY = "SECRET_SECRET_SECRET"
# common domain for the etherpad and django installation,
# e.g. ".example.com" (used for cross domain cookie)
ETHERPAD_DOMAIN = "localhost"
